global using Fix = FixedMathSharp.Fixed64;
global using Vector3 = FixedMathSharp.Vector3d;
global using Quaternion = FixedMathSharp.FixedQuaternion;
global using Pixagen.Core.App;
global using Pixagen.Core.Debugging;
global using Pixagen.Core.Input;
global using Pixagen.Core.Performance;
global using Pixagen.Core.Runtime;
global using Pixagen.Core.Timing;
global using Pixagen.Ecs.Runtime;
global using Pixagen.Rendering;
global using Pixagen.Rendering.Meshes;
global using Pixagen.Rendering.Raycasting;
global using Pixagen.Rendering.Textures;
global using Pixagen.Rendering.Vulkan;
global using Pixagen.Game.Features.SharedFeature.Components;
